version: '3'
networks:
  backend:
    driver: bridge
services:
  app:
    build: .
    container_name: app
    image: staveesh/qosmon
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
      - "${TCP_SERVER_PORT}:${TCP_SERVER_PORT}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    links:
      - influxdb
      - mongodb
    env_file:
      - .env
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
    environment:
      INFLUXDB_DB: "${INFLUXDB_NAME}"
      INFLUXDB_USER: "${INFLUXDB_USERNAME}"
      INFLUXDB_USER_PASSWORD: "${INFLUXDB_PASSWORD}"
    volumes:
      - /var/lib/qosmon/influxdb:/var/lib/influxdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: "${MONGODB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - /var/lib/qosmon/mongodb:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
